### ISSUE TITLE
PWM cannot packageing a jni library

### ISSUE THREAD

**Issue by toni1727** [technexion-android/platform_external_libgpiod#2]
Hello, I have followed this tutorial:

https://www.technexion.com/support/knowledgebase/using-pwm-from-a-linux-shell/

echo 0 > /sys/class/pwm/pwmchip1/export
echo 1000000 > /sys/class/pwm/pwmchip1/pwm0/period
echo 500000 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip1/pwm0/enable

This won't work in android app because "/sys/class/pwm/pwmchip1/export" will create the pwm files with the "root" user

on internet I found this solution:

sudo nano /etc/udev/rules.d/99-com.rules

SUBSYSTEM=="pwm*", PROGRAM="/bin/sh -c '\
        chown -R root:gpio /sys/class/pwm && chmod -R 770 /sys/class/pwm;\
        chown -R root:gpio /sys/devices/platform/soc/*.pwm/pwm/pwmchip* && chmod -R 770 /sys/devices/platform/soc/*.pwm/pwm/pwmchip*\
		
But I don't find the file  "/etc/udev/rules.d/99-com.rules"
		
In the other hand. I need this PWM2_OUT.

is this signal? -> /sys/class/pwm/pwmchip1/pwm0/

Or how can I activate that output?

Best regards.

**Comment by toni1727** [comment]
Hi again!

Will it work if I add these lines into /device/fsl/imx8m/pico_imx8mm/ueventd.freescale.rc ?

```
/sys/devices/platform/*.pwm/pwm/pwmchip*/pwm*/enable 0666 system system
/sys/devices/platform/*.pwm/pwm/pwmchip*/pwm*/period 0666 system system
/sys/devices/platform/*.pwm/pwm/pwmchip*/pwm*/duty_cycle 0666 system system
/sys/devices/platform/*.pwm/pwm/pwmchip*/pwm*/polarity   0666 system system


/sys/class/pwm/pwmchip*/export 0666 system system
/sys/class/pwm/pwmchip*/unexport 0666 system system

/sys/class/pwm/pwmchip*/pwm*/enable 0666 system system
/sys/class/pwm/pwmchip*/pwm*/period 0666 system system
/sys/class/pwm/pwmchip*/pwm*/duty_cycle 0666 system system
/sys/class/pwm/pwmchip*/pwm*/polarity   0666 system system
```

Best regards.

**Comment by wigcheng** [comment]
Sorry for late response, took a trip recently.
I think you should confirm it works using command-line first, then move the permission to the source code configuration file.

After I saw your problems, I think you do everything okay on command-line but failed when using app, right? If yes, please do important steps such as create/remove pwm node in inir.rc. I recommend the app only do read/write is better, please try again and let me know if it works, thanks.

**Comment by toni1727** [comment]
Thank you very much.

Yes, it works with commands, but I have problems with Android app.

What do you mean with inir.rc? I have to export the pwm, and only enable or disable throught the android app?

Could you guide me? I have no experience with the file inir.rc.

Won't it work with changes in the ueventd.freescale.rc file?

I also have to change the .dts file to enable pwm_2 output

Best regards.

**Comment by wigcheng** [comment]
Yes, you can add the export command to the init.rc: device/fsl/imx8m/pico_imx8mm/init.rc
And re-compile again, it should be works.

I think the you also need add permission to ueventd.freescale.rc file because your app still need to control it, isn't it?

Thanks

**Comment by toni1727** [comment]
Hello again!

I have 4 issues trying solving the problem.

**1) imx8mm-pico-pi.dts**
This does not seem enough to activate the PWM_2 gpio pin output
```
&iomuxc {
	imx8mm-pico {
		pinctrl_fan_pwm: fan_pwm {
			fsl,pins = <
				MX8MM_IOMUXC_SPDIF_RX_PWM2_OUT			0x16	
			>;
		};
         };
};
&pwm2 {
	pinctrl-names = "default";
	pinctrl-0 = <&pinctrl_fan_pwm>;
	status = "okay";
};
```


**2) on init.imx8mm.rc**
This seems not to activate the PWM and does not assign permissions either.
```
on property:sys.boot_completed=1
    # enabled pwm 2 and set permissions
	chmod -R 666 /sys/class/pwm
	echo 0 > /sys/class/pwm/pwmchip1/export
	chmod -R 666 /sys/class/pwm
    # enabled pwm 2 and set permissions
```

**3) on ueventd.freescale.rc**
This does not seem to have any effect on the permissions of the PWM

```
/dev/gpiochip0 0666 system system
/dev/gpiochip1 0666 system system
/dev/gpiochip2 0666 system system
/dev/gpiochip3 0666 system system
/dev/gpiochip4 0666 system system
/dev/i2c-0 0666 system system
/dev/i2c-1 0666 system system
/dev/i2c-2 0666 system system

/sys/class/pwm/pwmchip1/export 0666 system system
/sys/class/pwm/pwmchip1/npwm 0666 system system
/sys/class/pwm/pwmchip1/uevent 0666 system system
/sys/class/pwm/pwmchip1/unexport 0666 system system

/sys/class/pwm/pwmchip1/pwm0/enable 0666 system system
/sys/class/pwm/pwmchip1/pwm0/period 0666 system system
/sys/class/pwm/pwmchip1/pwm0/duty_cycle 0666 system system
/sys/class/pwm/pwmchip1/pwm0/polarity   0666 system system
```
(gpiochip* and i2c-* work at least)

**I ejecute this:**
but it seems not to work
```
echo 0 > /sys/class/pwm/pwmchip1/export
echo 1000000 > /sys/class/pwm/pwmchip1/pwm0/period
echo 100000 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle
echo 1 > /sys/class/pwm/pwmchip1/pwm0/enable
```
Do I need to configure other things?

In an example of the internet they do this too:

```
Enable Pin -> echo 12 > /sys/class/gpio/export
Set as an output pin -> echo out > /sys/class/gpio/gpio12/direction
Set the mode as PWM -> echo mode1 > /sys/kernel/debug/gpio_debug/gpio12/current_pinmux
```

**4) after "cook"**

I don't know why, but it doesn't generate the files.

"u-boot-imx8mm.imx" and "u-boot-imx8mm-evk-uuu.imx"

and it gives me error when executing -> uuu_imx_android_flash -f imx8mm

Thank you very much!

**Comment by wigcheng** [comment]
Hello

1. Do you flash the image before? Just issue "uuu_flashcard 7" command is enough, please use this command and try again, u-boot images is be generated when uuu_flashcard processing.

2. Please double check your compile is success, there's no output images if compile failed with error messages.

3. Please modify init script on init.rc instead of init.imx8mm.rc, you're modify the wrong script. And try to add your init part above "on init" line. The easy way to verification your init script is check the pwm node is generate success after boot up.

4. uevent file and device tree file seems no problems, you just need double check you control the right pwm node in system, but I think it's no problems because you already try it using command-line, right?

Thanks

**Comment by toni1727** [comment]
Hi!

1) The compile is success, a lot of warnings but at the end "success"
2) Ok, I will do "on init" instead.
3) I using the command-line and I activate the "pwm" but there is not output reading with oscilloscope

Best regards.

**Comment by toni1727** [comment]
still not working, attached configuration files and screenshots :(

[imx8mm files.zip](https://github.com/technexion-android/platform_external_libgpiod/files/3819226/imx8mm.files.zip)

**Comment by toni1727** [comment]
still not working, attached configuration files and screenshots

[imx8mm files.zip](https://github.com/technexion-android/platform_external_libgpiod/files/3819291/imx8mm.files.zip)

I use these commands too:

```
echo 0 > /sys/class/pwm/pwmchip1/export
chmod -R 777 /sys/class/pwm;
chmod -R 777 /sys/devices/platform/*.pwm;
setenforce 0
echo 1000000 > /sys/class/pwm/pwmchip1/pwm0/period;
echo 100000 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle;
echo 1 > /sys/class/pwm/pwmchip1/pwm0/enable

echo 0 > /sys/class/pwm/pwmchip2/export
chmod -R 777 /sys/class/pwm;
chmod -R 777 /sys/devices/platform/*.pwm;
setenforce 0
echo 1000000 > /sys/class/pwm/pwmchip2/pwm0/period;
echo 100000 > /sys/class/pwm/pwmchip2/pwm0/duty_cycle;
echo 1 > /sys/class/pwm/pwmchip2/pwm0/enable

echo 0 > /sys/class/pwm/pwmchip3/export
chmod -R 777 /sys/class/pwm;
chmod -R 777 /sys/devices/platform/*.pwm;
setenforce 0
echo 1000000 > /sys/class/pwm/pwmchip3/pwm0/period;
echo 100000 > /sys/class/pwm/pwmchip3/pwm0/duty_cycle;
echo 1 > /sys/class/pwm/pwmchip3/pwm0/enable

cd /sys/kernel/debug/
cat pwm
```

**Result:**

![image](https://user-images.githubusercontent.com/11811056/68395396-f0225180-016f-11ea-9789-0c0318f72f0e.png)


**But nothing comes out of the PWM outputs!**

Best regards

**Comment by toni1727** [comment]
I still can't fix it :(

**Comment by wigcheng** [comment]
Let's clear up from start what you want:

1. Which pwm interface is you want? Because I saw you just tried every different pwm node, but I think you only need one, right? And I also remember you tried success for the one of these pwm using command-line, right? which one is you test before? Do you ever modify the dts file before?

2. It seems it's not easy to auto generate the pwm node using init.rc because of the permission issue, so I think solve other issues is better such as pwm node confirm, uevent file setting, and running on selinux disabling mode, then issue commands to generate pwm node manually, if it works fine on app, then you can start develop how to generate pwm node automatically in Android system, how do you think?

Thanks

**Comment by toni1727** [comment]
**1.1 Which pwm interface is you want?** 
- I only need PWM2
**1.2 And I also remember you tried success for the one of these pwm using command-line, right?**
- I success "Executing" command-line (with the permissions issue) but I didnt test the real output working.
**1.3 Do you ever modify the dts file before?**
- No, I didn't

2
I would like to do it in the easiest way possible. I will use this board for iot without a screen.

I want full access with any application. Without worrying about permissions.

It also seems that the pwm needs more settings to activate the output. Because it seems that I activate the pwm, (when calling the "cat pwm" command it is seen) but the output does nothing.

how can I do it?

Best regards.

**Comment by wigcheng** [comment]
I checked the pwm configuration in pico-imx8mm dts file, there's only support pwm1(for panel backlight) and pwm4(fan), this is why you always failed using pwm2. I suggest you can test using pwm4 first because it has connector on the board, it's easy to debug!

Note that the pwm node name is a bit strange as following:
pwm1: /sys/class/pwm/pwmchip0
pwm4: /sys/class/pwm/pwmchip1

So you can control the pwm4 as following commands:
# cd /sys/class/pwm/pwmchip1
# echo 0 > export
# cd pwm0
# echo 1000000 > period
# echo 500000 > duty_cycle
# echo 1 > enable

I tested it and it works fine! So I think you can use it to test your app, then, add pwm2 support for you want to device tree file.

In addiiton, if you want to disable all permission, you can add "androidboot.selinux=permissive" argument to BOARD_KERNEL_CMDLINE variable of device/fsl/imx8m/pico_imx8mm/BoardConfig.mk path.

Thanks

**Comment by toni1727** [comment]
Did you checked my dts file? 
I attached it to you!

I cannot use these commands in the Android application:

```
cd /sys/class/pwm/pwmchip1
echo 0 > export
cd pwm0
echo 1000000 > period
echo 500000 > duty_cycle
echo 1 > enable
```
**I don't have read/write permissions !!**

and when the pwm0 folder is created, neither

I added these lines in the ueventd.freescale.rc file

```
/sys/class/pwm/pwmchip1/export 0666 system system
/sys/class/pwm/pwmchip1/unexport 0666 system system
/sys/class/pwm/pwmchip1/pwm0/enable 0666 system system
/sys/class/pwm/pwmchip1/pwm0/period 0666 system system
/sys/class/pwm/pwmchip1/pwm0/duty_cycle 0666 system system
/sys/class/pwm/pwmchip1/pwm0/polarity 0666 system system
```

**BUT DOES NOT WORK!!**

I also added pwm2 and pwm3 in the dts file.

**Please check what I have sent you.**

**Comment by toni1727** [comment]
Also I added this patch:

https://patchwork.ozlabs.org/patch/977237/

I don't know if it is valid for Android. The point is that I don't know where to place:

```
SUBSYSTEM=="pwm*", PROGRAM="/bin/sh -c '\
        chown -R root:gpio /sys/class/pwm && chmod -R 770 /sys/class/pwm;\
        chown -R root:gpio
/sys/devices/platform/soc/*.pwm/pwm/pwmchip* && chmod -R 770
/sys/devices/platform/soc/*.pwm/pwm/pwmchip*\
```

**Comment by wigcheng** [comment]
I checked your device tree file and it seems re-definition for your pwm2 pin:
search MX8MM_IOMUXC_SPDIF_RX_PWM2_OUT and MX8MM_IOMUXC_SPDIF_RX_GPIO5_IO4.
Please take out that GPIO one and try again, other pins that you modified also need double check again,please.

In addition, I doubt why you don't want to try PWM using exist PWM node from official release first such as above for pwm4 example, I'm sure it works using command-line, and you need confirm your app can access, if you modify dts and app at the same time, it will easy to confuse and difficult to find the ways.

Thanks

**Comment by toni1727** [comment]
Thank you very much,

I already deleted MX8MM_IOMUXC_SPDIF_RX_GPIO5_IO4 but same result :(

I don't use pwm4 because I don't have the base board. I only have access to pwm2..

**Comment by wigcheng** [comment]
Any update?

**Comment by toni1727** [comment]
Not at all, I'm still waiting for you to help me with a solution.

PWM2 output doesn't work.

Maybe some configuration is missing, or something is wrongly configured.

**Comment by wigcheng** [comment]
Don't forget close this issue if you solve it already :)

**Comment by toni1727** [comment]
In the end I did a "trick" and initialized the pwm in the init.rc file.

It's sad that the uevents don't work

it would be necessary to fix the pwm driver for uvents to work.

something like this:

https://coral.googlesource.com/linux-imx/+/1595d0453afebd96b49457791502058895a02211

Best regards!
