### ISSUE TITLE
Cannot get commands to work in shell

### ISSUE THREAD

**Issue by mignacio** [technexion-android/platform_external_libgpiod#3]
Hello, I've followed the instructions described in the readme.md file.

However after building and flashing the image I get "file not found" response in the adb shell after trying all of the library commands, none of them seem to work.

Is there anything I should also take into account that it is not described in the readme?
Or how can I go about to debug and make sure that the library was correctly builded and included in the AOSP image?

Thank you.

**Comment by wigcheng** [comment]
Which platform did you use?
I think you should didn't use our products, you need compile it manually if you use this repo to other AOSP projects.
issue command "mm" in external/libgpiod should be works.

These utilities just need libgpiod.so is enough.
Thanks

**Comment by wigcheng** [comment]
Any update?
